version: "3.5"
services:
  web:
    hostname: web
    domainname: docker
    container_name: ${COMPOSE_PROJECT_NAME}.web
    restart: always
    image: ${REPO}/${COMPOSE_PROJECT_NAME}/web:${TAG}
    healthcheck:
        test: ["CMD", "curl", "-v", "localhost"]
        start_period: 30s
        interval: 10s
        timeout: 10s
        retries: 10
    environment:
      - VIRTUAL_HOST=johanleroux.me,www.johanleroux.me
      - LETSENCRYPT_HOST=johanleroux.me,www.johanleroux.me
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
